import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/components/react-query-provider";
import { ThemeApplier } from "@/components/features/theme/ThemeApplier";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2026 Next App",
  description: "Generated by Trae with Vercel Best Practices",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "bg-background text-foreground")} suppressHydrationWarning>
        <ReactQueryProvider>
          <ThemeApplier />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
